<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.zmuxio</groupId>
        <artifactId>zmux-parent</artifactId>
        <version>1.0.4</version>
    </parent>

    <artifactId>zmux</artifactId>
    <name>zmux</name>
    <description>Core Java implementation of the ZMux multiplexing protocol.</description>
    <url>https://github.com/zmuxio/zmux-java/tree/main/zmux</url>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
